Algoritmo "Algoritmo leitura antecessor"
// 
//  
// Descrição   : Escreva um algoritmo para ler um valor (do teclado) e escrever
// (na tela) o seu antecessor.
// Autor(a)    : Veronica Thais Gomes de Oliveira
// Data atual  : 21/05/2022
Var

valor : inteiro

Inicio

escreva ("Digite um valor: ")
leia (valor)

valor <- valor -1

escreval ("O seu antecessor é: ", valor)


Fimalgoritmo